name: AgriTech---USGS-LIDAR-package
on: 
  push:
    branches:
    - master
jobs:
  run:
    runs-on: ubuntu-latest 
    container:  docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      run: | 
        sudo pip3 install -r requirements.txt
        python src/script.py
    - name: run-tests
      run: |
        python -m unittest tests.unittesting
